name: duplo

dependencies:
  - base
  - comonad
  - fastsum
  - free
  - mtl
  - pretty
  - text

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralisedNewtypeDeriving
  - LambdaCase
  - MagicHash
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - ViewPatterns

ghc-options:
  - -freverse-errors
  - -Weverything
  - -Wno-missing-import-lists
  - -Wno-unsafe
  - -Wno-safe
  - -Wno-implicit-prelude
  - -Wno-missing-safe-haskell-mode
  - -Wno-prepositive-qualified-module

library:
  source-dirs:
    - src/
